version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - GIT_AUTHOR=${GIT_AUTHOR}
        - GIT_REPOSITORY=${GIT_REPOSITORY}
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./:/go/src/github.com/${GIT_AUTHOR}/${GIT_REPOSITORY}
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
